# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Mehrab Khavari
title: B.Sc.  Biomedical Engineering, Bio Electric	
email: Khavarimehrab80@gmail.com
website: https://mehrabkhavari.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  Mehrabkhavari
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: mehrabkhavari.ir
linkedin_username: Mehrabkhavari
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Brett and I'm a senior network system administrator. As well as administrating systems I also have experience making software and web apps. I have worked at a number of companies gaining teamwork and leadership skills.

  I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

content:
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: B.Sc.  Biomedical Engineering, Bio Electric
        caption: September 2019 - Present
        sub_title: 
        quote: >
          Overall GPA: 16/20 (80%)
          Major GPA: 16.37/20 (81.8%)
        description: | # this will include new lines to allow paragraphs
          Islamic Azad University, Central Tehran Branch, Tehran, Iran  <br /> 
          Note: Azad University is the second best university in Iran based on U.S.news <br/> <br/>
          

  - title: Research Intrest # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: 
        description: | # this will include new lines to allow paragraphs
          Robotic, Electronics, Hardware Developing, Reverse Engineering, Embedded units programming. <br/> <br/>    
        
  - title: Awards AND Honors # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        quote: >
          
        description: | # this will include new lines to allow paragraphs
          •	Participation in the FIRA RoboWorld Competition – Innovation and Business 
            league, Wolfenbüttel, Germany. 							<mark>	July 21, 2023 </mark> <br/>
          •	Second Place in Global Robocop Competition – Rescue league, Nagoya, Japan. 		<mark> July 27, 2017</mark> <br/>
          •	Third Place in the Iran Open Robocop Competition as a Coach, Tehran, Iran.	<mark> April 27, 2023 </mark> <br/>
          •	Second Place in the Iran Open Robocop Competition, Tehran, Iran.				<mark>April 5, 2017</mark> <br/>

          
  - title: Academic Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: 
        link: 
        # link_text: Project Website
        additional_links:
          - title: 
            
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          
        description: | # this will include new lines to allow paragraphs
          <b> •	Logic Circuit Simulator (Voluntary university project) </b> <br/> 
          <small> &nbsp; &nbsp; &nbsp; Designed Schematic of Electrical circuit.</small> <br/>
          <small>&nbsp; &nbsp; &nbsp; Designed, manufactured, and assembled PCB.</small> <br/>
          <small>&nbsp; &nbsp; &nbsp; Utilized a 3D printer to create the housing </small> <br/>
          <b> • Class Projects </b> <br/>
          <small>&nbsp; &nbsp; &nbsp; Completed various class projects, including Smart Lights, Audio Amplifier, and voltage Multiplier.</small> <br/>

          
  - title: Other Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: 
        link: 
        # link_text: Project Website
        additional_links:
          - title: 
            
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          
        description: | # this will include new lines to allow paragraphs
          <b> •	Reverse Engineering Projects for Medical Equipment </b> <br/> 
          <small> &nbsp; &nbsp; &nbsp;	Disassembled circuit elements.</small> <br/>
          <small>&nbsp; &nbsp; &nbsp; 	Created circuit schematics based on the board. </small> <br/>
          <small>&nbsp; &nbsp; &nbsp; 	Designed, manufactured and assembled PCB. </small> <br/>
          <b> •	Building a 3D Printer </b> <br/>
          <small>&nbsp; &nbsp; &nbsp; 	Researched and listed required components. </small> <br/>
          <small>&nbsp; &nbsp; &nbsp; 	Customized certain components for performance enhancements.  </small> <br/>
          <small>&nbsp; &nbsp; &nbsp; 	Assembled the device following instructions. </small> <br/>
          <small>&nbsp; &nbsp; &nbsp; 	Conducted Initial setup and calibration.  </small> <br/>
          <b> •	Apartment Warehouses Wiring Project </b> <br/>
          <small>&nbsp; &nbsp; &nbsp; 		Created wiring diagrams. </small> <br/>
          <small>&nbsp; &nbsp; &nbsp; 		Performed intubation and wiring.  </small> <br/>
          <small>&nbsp; &nbsp; &nbsp; 		Installed necessary equipment.  </small> <br/>
          <b> •	Full Color Infinity Mirror </b> <br/>
          <small>&nbsp; &nbsp; &nbsp; 	Selected appropriate lamps and glass materials. </small> <br/>
          <small>&nbsp; &nbsp; &nbsp; 	Researched and improved mirror reflection and transparency.  </small> <br/>
          <small>&nbsp; &nbsp; &nbsp; 	Iteratively upgraded the product's electronics and mirrors.  </small> <br/>
          <small>&nbsp; &nbsp; &nbsp; 	Produced and marketed the final product.   </small> <br/>
          <b> •	Smart Home project </b> <br/>
          <small>&nbsp; &nbsp; &nbsp; 	Implemented smart controls for curtains, lights, and air conditioner. </small> <br/>
          <small>&nbsp; &nbsp; &nbsp; 	Designed and constructed a central hub.  </small> <br/>
          <small>&nbsp; &nbsp; &nbsp; 	Wrote codes. </small> <br/>
          <small>&nbsp; &nbsp; &nbsp; 	Design and Build Electric Boards.   </small> <br/>
          
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Academic Experience
        # link_text: boringcompany.com
        
        description: | # this will include new lines to allow paragraphs
          •	Miniature Talk Competition at Children’s Hospital, Tehran, Iran. 		<mark>	September 9, 2023 </mark> <br/>
          •	Certification in proficiency in Surgery Room Medical Equipment Maintenance and Troubleshooting.	 		<mark> August 13, 2022</mark> <br/>
          •	Certification in proficiency in Electronic in Medical Engineering.		<mark> August 20, 2022 </mark> <br/>
          •	Attended the ROS and Python Workshop.				<mark>August 20, 2022</mark> <br/>      
      - layout: left
        title: Engineering Experience
        # link_text: boringcompany.com
        
        description: | # this will include new lines to allow paragraphs
          •	Certification in proficiency in Embedded C Programming.		<mark>	June 2, 2023 </mark> <br/>
          •	Certification in proficiency in Embedded ARM Programming.			 		<mark> June 2, 2023</mark> <br/>
          •	Certification in expertise in Altium Designer. 		<mark> May 7, 2020 </mark> <br/>
          •	Certification in expertise in Single Phase and Three Phase Electricity.				<mark>November 14, 2019</mark> <br/>    
          •	Technical skills in Installation of CCTV Cameras.				<mark>July 24, 2017</mark> <br/>    
          •	Technical skills in Installation and Service of Traction Elevators.				<mark>June 15, 2017</mark> <br/>    
      - layout: left
        title: Teaching Experience
        # link_text: boringcompany.com
        
        description: | # this will include new lines to allow paragraphs
          •	Taught Robotics at Saratech Primary school.			<mark>	2022 - 2023 </mark> <br/>
          •	Taught Robotic and Arduino Programing at Salam High School.			 		<mark> 2022 - 2023 </mark> <br/>
      
  - title: Publication # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout:
        title: 
        link: 
        # link_text: Project Website
        additional_links:
          - title: 
            
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          
        description: | # this will include new lines to allow paragraphs
        
  - title: Skills # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: 
        link: 
        # link_text: Project Website
        additional_links:
          - title: 
            
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          
        description: | # this will include new lines to allow paragraphs
          <b> •	Computer Skills: </b> <br/> 
          <b><i> &nbsp; &nbsp;	Programming Languages: </i></b> <br/>
          <small>&nbsp; &nbsp; &nbsp; &nbsp; 	C </small> <br/>
          <small>&nbsp; &nbsp; &nbsp; &nbsp; 	C++ </small> <br/>
          <small>&nbsp; &nbsp; &nbsp; &nbsp; 	Assembly </small> <br/>
          <small>&nbsp; &nbsp; &nbsp; &nbsp; 	Arduino </small> <br/>
          <b><i> &nbsp; &nbsp;	Software: </i></b> <br/>
          <small>&nbsp; &nbsp; &nbsp; &nbsp; 	Proteus circuit simulator </small> <br/>
          <small>&nbsp; &nbsp; &nbsp; &nbsp; 		Keil uVision </small> <br/>
          <small>&nbsp; &nbsp; &nbsp; &nbsp; 		Code blocks </small> <br/>
          <small>&nbsp; &nbsp; &nbsp; &nbsp; 		Code vision </small> <br/>
          <small>&nbsp; &nbsp; &nbsp; &nbsp; 		Anaconda </small> <br/>
          <small>&nbsp; &nbsp; &nbsp; &nbsp; 		Arduino IDLE </small> <br/>
          <small>&nbsp; &nbsp; &nbsp; &nbsp; 	  Microsoft Office </small> <br/>
          <small>&nbsp; &nbsp; &nbsp; &nbsp; 		Camtasia </small> <br/>
          <small>&nbsp; &nbsp; &nbsp; &nbsp; 		Trello </small> <br/>
          <small>&nbsp; &nbsp; &nbsp; &nbsp; 	  Jira</small> <br/>
          <b><i> &nbsp; &nbsp;	Hardware: </i></b> <br/>
          <small>&nbsp; &nbsp; &nbsp; &nbsp; 		  Types of Arduino Boards </small> <br/>
          <small>&nbsp; &nbsp; &nbsp; &nbsp; 			Types of ESP Boards </small> <br/>
          <small>&nbsp; &nbsp; &nbsp; &nbsp; 			Blue pill </small> <br/>
          <small>&nbsp; &nbsp; &nbsp; &nbsp; 			Mini pc, Nano pc </small> <br/>
          <small>&nbsp; &nbsp; &nbsp; &nbsp; 			Ramps – RepRap </small> <br/>
          <small>&nbsp; &nbsp; &nbsp; &nbsp; 		  Step Motors </small> <br/>
          <small>&nbsp; &nbsp; &nbsp; &nbsp; 	  	Types of ARM microcontrollers </small> <br/>
          <small>&nbsp; &nbsp; &nbsp; &nbsp; 			Types of AVR microcontrollers </small> <br/>
          <small>&nbsp; &nbsp; &nbsp; &nbsp; 			Servo motors </small> <br/>
           <b><i> &nbsp; &nbsp;	OS: </i></b> <br/>
          <small>&nbsp; &nbsp; &nbsp; &nbsp; 		  Windows </small> <br/>
          <small>&nbsp; &nbsp; &nbsp; &nbsp; 			Ubuntu </small> <br/>
          <small>&nbsp; &nbsp; &nbsp; &nbsp; 			macOS </small> <br/>
          <small>&nbsp; &nbsp; &nbsp; &nbsp; 			ROS </small> <br/>
          <b> •	Language Skills: </b> <br/> 
          <small>&nbsp; &nbsp; &nbsp; &nbsp; 		  English (soon) </small> <br/>
          <small>&nbsp; &nbsp; &nbsp; &nbsp; 			French (Beginner) </small> <br/>
          <small>&nbsp; &nbsp; &nbsp; &nbsp; 			Persian (Native( </small> <br/>
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
