# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Mehrab Khavari
title: B.Sc.  Biomedical Engineering, Bio Electric	
email: Khavarimehrab80@gmail.com
website: https://mehrabkhavari.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  Mehrabkhavari
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: mehrabkhavari.ir
linkedin_username: Mehrabkhavari
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Brett and I'm a senior network system administrator. As well as administrating systems I also have experience making software and web apps. I have worked at a number of companies gaining teamwork and leadership skills.

  I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

content:
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: B.Sc.  Biomedical Engineering, Bio Electric
        caption: September 2019 - Present
        sub_title: 
        quote: >
          Overall GPA: 16/20 (80%)
          Major GPA: 16.37/20 (81.8%)
        description: | # this will include new lines to allow paragraphs
          Islamic Azad University, Central Tehran Branch, Tehran, Iran  <br /> 
          Note: Azad University is the second best university in Iran based on U.S.news <br/> <br/>
          

  - title: Research Intrest # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: 
        description: | # this will include new lines to allow paragraphs
          Robotic, Electronics, Hardware Developing, Reverse Engineering, Embedded units programming. <br/> <br/>    
        
  - title: Awards AND Honors # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        quote: >
          
        description: | # this will include new lines to allow paragraphs
          •	Participation in the FIRA RoboWorld Competition – Innovation and Business 
            league, Wolfenbüttel, Germany. 							<mark>	July 21, 2023 </mark> <br/>
          •	Second Place in Global Robocop Competition – Rescue league, Nagoya, Japan. 		<mark> July 27, 2017</mark> <br/>
          •	Third Place in the Iran Open Robocop Competition as a Coach, Tehran, Iran.	<mark> April 27, 2023 </mark> <br/>
          •	Second Place in the Iran Open Robocop Competition, Tehran, Iran.				<mark>April 5, 2017</mark> <br/>

          
  - title: Academic Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          
        description: | # this will include new lines to allow paragraphs
          <b> •	Logic Circuit Simulator (Voluntary university project) </b> <br/> 
          <small> &nbsp; &nbsp; &nbsp; Designed Schematic of Electrical circuit.</small> <br/>
          <small>&nbsp; &nbsp; &nbsp; Designed, manufactured, and assembled PCB.</small> <br/>
          <small>Utilized a 3D printer to create the housing </small> <br/>
          <b> • Class Projects </b> <br/>
          <small>Completed various class projects, including Smart Lights, Audio Amplifier, and voltage Multiplier.</small> <br/>


  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: The Boring Company
        link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Senior Network System Administrator
        caption: November 2017 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.



  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
